//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAlquilerAutos.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.Devoluciones = new HashSet<Devolucione>();
            this.Incidencias = new HashSet<Incidencia>();
            this.Accesorios = new HashSet<Accesorio>();
        }
    
        public int ReservaID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public string PlacaVeh { get; set; }
        public Nullable<int> LugarEntrega_Devolucion { get; set; }
        public Nullable<int> SeguroID { get; set; }
        public Nullable<System.DateTime> FechaReserva { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinalizacion { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        [JsonIgnore]
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Devolucione> Devoluciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Incidencia> Incidencias { get; set; }
        [JsonIgnore]
        public virtual Ubicacione Ubicacione { get; set; }
        [JsonIgnore]
        public virtual Vehiculo Vehiculo { get; set; }
        [JsonIgnore]
        public virtual Seguro Seguro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Accesorio> Accesorios { get; set; }
    }
}
